// <auto-generated />
using System;
using Lumen.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lumen.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408130057_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lumen.API.Models.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetKey = "panda",
                            Description = "Calm and cozy panda",
                            Name = "Panda"
                        },
                        new
                        {
                            Id = 2,
                            AssetKey = "pig",
                            Description = "Cheerful little pig",
                            Name = "Pig"
                        });
                });

            modelBuilder.Entity("Lumen.API.Models.Entities.ChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyRecordId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DailyRecordId");

                    b.ToTable("ChecklistItems");
                });

            modelBuilder.Entity("Lumen.API.Models.Entities.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("Lumen.API.Models.Entities.DailyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("DailyRecords");
                });

            modelBuilder.Entity("Lumen.API.Models.Entities.FoodLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyRecordId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.Property<int>("MealType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DailyRecordId", "MealType")
                        .IsUnique();

                    b.ToTable("FoodLogs");
                });

            modelBuilder.Entity("Lumen.API.Models.Entities.MoodLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mood")
                        .HasColumnType("integer");

                    b.Property<int>("TimeSlot")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DailyRecordId", "TimeSlot")
                        .IsUnique();

                    b.ToTable("MoodLogs");
                });

            modelBuilder.Entity("Lumen.API.Models.Entities.SleepLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyRecordId")
                        .HasColumnType("uuid");

                    b.Property<float>("HoursSlept")
                        .HasColumnType("real");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DailyRecordId")
                        .IsUnique();

                    b.ToTable("SleepLogs");
                });

            modelBuilder.Entity("Lumen.API.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Lumen.API.Models.Entities.ChecklistItem", b =>
                {
                    b.HasOne("Lumen.API.Models.Entities.DailyRecord", "DailyRecord")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("DailyRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyRecord");
                });

            modelBuilder.Entity("Lumen.API.Models.Entities.DailyRecord", b =>
                {
                    b.HasOne("Lumen.API.Models.Entities.User", "User")
                        .WithMany("DailyRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lumen.API.Models.Entities.FoodLog", b =>
                {
                    b.HasOne("Lumen.API.Models.Entities.DailyRecord", "DailyRecord")
                        .WithMany("FoodLogs")
                        .HasForeignKey("DailyRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyRecord");
                });

            modelBuilder.Entity("Lumen.API.Models.Entities.MoodLog", b =>
                {
                    b.HasOne("Lumen.API.Models.Entities.DailyRecord", "DailyRecord")
                        .WithMany("MoodLogs")
                        .HasForeignKey("DailyRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyRecord");
                });

            modelBuilder.Entity("Lumen.API.Models.Entities.SleepLog", b =>
                {
                    b.HasOne("Lumen.API.Models.Entities.DailyRecord", "DailyRecord")
                        .WithOne("SleepLog")
                        .HasForeignKey("Lumen.API.Models.Entities.SleepLog", "DailyRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyRecord");
                });

            modelBuilder.Entity("Lumen.API.Models.Entities.User", b =>
                {
                    b.HasOne("Lumen.API.Models.Entities.Character", "Character")
                        .WithMany("Users")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lumen.API.Models.Entities.Connection", "Connection")
                        .WithMany("Users")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Character");

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("Lumen.API.Models.Entities.Character", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Lumen.API.Models.Entities.Connection", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Lumen.API.Models.Entities.DailyRecord", b =>
                {
                    b.Navigation("ChecklistItems");

                    b.Navigation("FoodLogs");

                    b.Navigation("MoodLogs");

                    b.Navigation("SleepLog");
                });

            modelBuilder.Entity("Lumen.API.Models.Entities.User", b =>
                {
                    b.Navigation("DailyRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
